behaviors:
    CarBehaviour:
        trainer_type: ppo
        hyperparameters:
            batch_size: 512 
            buffer_size: 4096
            learning_rate_schedule: linear
            learning_rate: 3.0e-4
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
        network_settings:
            hidden_units: 512
            normalize: false
            num_layers: 4
            vis_encode_type: simple
            memory:
                memory_size: 512
                sequence_length: 512
        reward_signals:
          extrinsic:
            gamma: 0.99
            strength: 1.0
          gail:
            strength: 0.5
            demo_path: D:\MachineLearning\SelfDriving\demo\Selfdrive.demo
        behavioral_cloning:
            strength: 0.5
            demo_path: D:\MachineLearning\SelfDriving\demo\Selfdrive.demo
        max_steps: 10.0e6
        time_horizon: 64    
        summary_freq: 10000
        threaded: true